import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FC, ReactNode } from 'react';
import Header from './components/Header';
import Providers from './providers';
import './styles/reset.css';
import './styles/base.css';

const inter = Inter({ subsets: ['latin'] });

type RootLayoutProps = {
	children: ReactNode;
};

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
};
export default RootLayout;
